### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mlabarre** [aadsm/jsmediatags#67]
Hello
I run nodejs on a Macos Sierra without problem.
```
node -v
v7.5.0
```
```
npm -v
4.1.2
```
After an 
`npm install --save jsmediatags`
I include the following require in my code
`var jsmediatags = require("jsmediatags");`

Run result in:
```
node ./test.js
module.js:472
    throw err;
    ^
Error: Cannot find module 'jsmediatags'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/tests/test.js:11:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
Version:
```
npm outdated
Package      Current  Wanted  Latest  Location
jsmediatags    3.6.2     git     git  tests 

```
An idea ?
Many thanks

**Comment by mlabarre** [comment]
Npm problem. That's ok. Sorry
